#!/bin/bash

echo " -> Removing docker images"
docker rm -vf heroku-nginx-cedar-16

echo " -> Rebuilding the image from current directory"
docker build -t heroku-nginx-cedar-16 .

echo " -> Run the slave container"

# docker run -d --name heroku-nginx-cedar-16 \
#   -p 3001:80 \
#   heroku-nginx-cedar-16
#
# docker ps
# echo " -> Done. To shell into the container: docker exec -i -t heroku-nginx-cedar-16 bash"

docker run -it --rm --name heroku-nginx-cedar-16 \
  -p 3001:80 \
  -v /Users/klevo/www/nginx-buildpack/bin:/var/dummy_app/bin \
  -v /tmp/buildpack_cache:/var/buildpack_cache \
  heroku-nginx-cedar-16 bash

# -v /tmp/buildpack_cache:/var/buildpack_cache \
